//! Workflow definitions for CI/CD

use gh_workflow::Workflow;
use std::process::Command;

const GENERATED_HEADER: &str = "# -------------------------------------------------------------------\n# ------------------------------- WARNING ---------------------------\n#\n# This file was automatically generated by gh-workflows using the\n# gh-workflow-gen bin. You should add and commit this file to your\n# git repository. **DO NOT EDIT THIS FILE BY HAND!** Any manual changes\n# will be lost if the file is regenerated.\n#\n# -------------------------------------------------------------------\n# ----------------------------- END WARNING -------------------------\n# -------------------------------------------------------------------";

pub(crate) fn generate_workflow(workflow: Workflow, name: &str) {
    let root = String::from_utf8(
        Command::new("git")
            .args(["rev-parse", "--show-toplevel"])
            .output()
            .expect("git root")
            .stdout,
    )
    .expect("git root utf8");
    let path = std::path::PathBuf::from(root.trim())
        .join(".github/workflows")
        .join(name);
    let content = format!(
        "{}\n{}",
        GENERATED_HEADER,
        workflow.to_string().expect("workflow yaml")
    );
    let current = std::fs::read_to_string(&path).ok();
    let equivalent = current.as_deref().is_some_and(|existing| {
        existing == content
            || match (
                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(existing),
                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(&content),
            ) {
                (Ok(left), Ok(right)) => left == right,
                _ => false,
            }
    });
    if std::env::var_os("CI").is_some() {
        assert!(
            equivalent,
            "generated workflow is stale: {}",
            path.display()
        );
    } else if !equivalent {
        std::fs::write(&path, content).expect("write workflow");
    }
}

mod autofix;
mod bounty;
mod ci;
mod labels;
mod release_drafter;
mod release_publish;
mod stale;

pub use autofix::*;
pub use bounty::*;
pub use ci::*;
pub use labels::*;
pub use release_drafter::*;
pub use release_publish::*;
pub use stale::*;
