//! MCP server implementation: the three `civis_*` tools plus the rmcp
//! `ServerHandler` glue. Lives in its own module so the
//! `#[tool_router]`-generated code is isolated from the public library
//! helpers in `lib.rs` (which intentionally avoid `rmcp` re-exports so
//! unit tests can compile without pulling in the macro-generated code).

use std::path::PathBuf;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    schemars::JsonSchema,
    tool, tool_handler, tool_router, Json,
};
use serde::{Deserialize, Serialize};

/// MCP server that exposes the three `civis-cli` verification tools
/// (`civis_verify`, `civis_pixels`, `civis_census`). The router is
/// populated by the `#[tool_router]` macro on the impl block below.
#[derive(Clone, Default)]
pub struct CivisMcpServer {
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

impl CivisMcpServer {
    /// Build a fresh server instance with an empty tool router. The router
    /// itself is generated by the `#[tool_router]` macro and picks up
    /// every `#[tool]` method on the impl block below.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct VerifyArgs {
    /// Optional explicit PNG output path. Defaults to
    /// `target/verify-frames/frame-0.png` (matches `civis-cli`'s verify bin).
    #[schemars(description = "Optional explicit output PNG path")]
    pub out: Option<String>,
    /// Optional window width in logical pixels (default 640).
    #[schemars(description = "Window width in logical pixels (default 640)")]
    pub width: Option<u32>,
    /// Optional window height in logical pixels (default 360).
    #[schemars(description = "Window height in logical pixels (default 360)")]
    pub height: Option<u32>,
    /// Optional settle frames before the screenshot is triggered.
    #[schemars(description = "Frames to wait before capture (default 60)")]
    pub settle_frames: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct PixelsArgs {
    /// Path to a PNG file on disk. Use the path returned by `civis_verify`.
    pub path: String,
    /// Optional grid size (sample points per axis). Default 16.
    #[schemars(description = "Sample points per axis (default 16)")]
    pub grid: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct CensusArgs {
    /// Optional WebSocket host override. Default `127.0.0.1`.
    #[schemars(description = "WebSocket host override (env: CIV_WS_HOST)")]
    pub host: Option<String>,
    /// Optional WebSocket port override. Default 3000.
    #[schemars(description = "WebSocket port override (env: CIV_SERVER_PORT)")]
    pub port: Option<u16>,
    /// Optional per-request timeout in milliseconds. Default 5000.
    #[schemars(description = "Per-request timeout in ms (env: CIV_CENSUS_TIMEOUT_MS)")]
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct PixelsResult {
    pub path: String,
    pub grid: u32,
    pub stats: serde_json::Value,
    pub harness_version: &'static str,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct CensusResult {
    pub url: String,
    pub tick: u64,
    pub population: Option<u64>,
    pub live: bool,
    pub harness_version: &'static str,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct VerifyResultTool {
    pub output_path: String,
    pub settle_frames: u32,
    pub width: u32,
    pub height: u32,
    pub harness_version: &'static str,
    pub bevy_version: &'static str,
}

#[tool_router]
impl CivisMcpServer {
    /// Run the Bevy 0.18 frame-capture pipeline. Calls
    /// `civis_cli::verify::run_verify` directly — no `cargo run` shell-out.
    /// Returns a structured error when the `bevy` feature is disabled so
    /// agents that hit the path without rebuilding know exactly what to do.
    #[tool(
        name = "civis_verify",
        description = "Capture a single Bevy 0.18 frame to PNG and return the on-disk path. Requires the `bevy` feature at build time."
    )]
    async fn civis_verify(
        &self,
        Parameters(VerifyArgs {
            out,
            width,
            height,
            settle_frames,
        }): Parameters<VerifyArgs>,
    ) -> Result<Json<VerifyResultTool>, String> {
        #[cfg(feature = "bevy")]
        {
            use civis_cli::verify::{run_verify as cli_run_verify, VerifyOptions, BEVY_VERSION};

            let options = VerifyOptions {
                output_path: PathBuf::from(
                    out.unwrap_or_else(|| "target/verify-frames/frame-0.png".to_string()),
                ),
                settle_frames: settle_frames.unwrap_or(60),
                width: width.unwrap_or(640),
                height: height.unwrap_or(360),
            };
            let result = cli_run_verify(options).map_err(|err| format!("civis_verify: {err}"))?;
            Ok(Json(VerifyResultTool {
                output_path: result.output_path.to_string_lossy().to_string(),
                settle_frames: result.settle_frames,
                width: result.width,
                height: result.height,
                harness_version: civis_cli::HARNESS_VERSION,
                bevy_version: BEVY_VERSION,
            }))
        }
        #[cfg(not(feature = "bevy"))]
        {
            let _ = (out, width, height, settle_frames);
            Err("civis_verify requires the `bevy` feature; rebuild with `cargo build -p civis-mcp --features bevy`".to_string())
        }
    }

    /// Decode a PNG file and emit pixel statistics. Calls the pure
    /// `civis_cli::pixels::{sample_rgb_grid, compute_pixel_stats}` library
    /// functions; no Bevy or network involvement.
    #[tool(
        name = "civis_pixels",
        description = "Sample a regular RGB grid from a PNG file and emit pixel statistics (mean R/G/B, percent near-black, percent gray, distinct hue count). Pure offline — no renderer or network."
    )]
    async fn civis_pixels(
        &self,
        Parameters(PixelsArgs { path, grid }): Parameters<PixelsArgs>,
    ) -> Result<Json<PixelsResult>, String> {
        let grid_usize = grid.map(|g| g as usize).unwrap_or(16);
        let path_buf = PathBuf::from(&path);
        let payload = crate::pixels_tool_payload(&path_buf, grid_usize)?;
        let stats = payload
            .get("stats")
            .cloned()
            .ok_or_else(|| "pixels_tool_payload missing `stats`".to_string())?;
        Ok(Json(PixelsResult {
            path,
            grid: grid.unwrap_or(16),
            stats,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Query `sim.status` over the civ-server WebSocket JSON-RPC bridge.
    /// Calls `civis_cli::census::{build_sim_status_request, decode_response,
    /// validate_sim_status}` directly.
    #[tool(
        name = "civis_census",
        description = "Read sim.status from the civ-server JSON-RPC WebSocket bridge. Returns the live tick, population (if a sim is attached), and a derived `live` flag."
    )]
    async fn civis_census(
        &self,
        Parameters(CensusArgs {
            host,
            port,
            timeout_ms,
        }): Parameters<CensusArgs>,
    ) -> Result<Json<CensusResult>, String> {
        let mut config = crate::census_config_with_url();
        if let Some(host) = host {
            config.host = host;
        }
        if let Some(port) = port {
            config.port = port;
        }
        if let Some(timeout_ms) = timeout_ms {
            config.timeout_ms = timeout_ms;
        }
        let url = config.ws_url();
        let status =
            crate::census_sim_status(&config).map_err(|err| format!("civis_census: {err}"))?;
        Ok(Json(CensusResult {
            url,
            tick: status.tick,
            population: status.population,
            live: status.live,
            harness_version: crate::HARNESS_VERSION,
        }))
    }
}

#[tool_handler]
impl rmcp::ServerHandler for CivisMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
    }
}

/// Public shim that re-exposes the macro-generated `tool_router` inherent
/// method across the `lib`/`server` module boundary (the macro emits the
/// method as `pub(self)`, which is invisible from sibling modules).
pub fn registered_router() -> ToolRouter<CivisMcpServer> {
    CivisMcpServer::tool_router()
}
