name: test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

env:
  RUSTFLAGS: '-Dwarnings'
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo nextest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install SQLite
        run: sudo apt-get install -y libsqlite3-dev
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: cargo nextest run
        run: cargo nextest run --all-features --workspace
